roberms/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views, views

from roberms import settings


urlpatterns = [
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(
        template_name='r/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='r/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='r/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='r/password_reset_complete.html'), name='password_reset_complete'),
    # url('^', include('django.contrib.auth.urls')),


    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('roberms/super/admin/', admin.site.urls),

    path('', include('sms.urls')),
    path('sms/v1/', include('sms_api.urls')),
    path('roberms/admin/', include('roberms_admin.urls')),
    path('roberms/salesperson/', include('salesperson.urls')),
    path('invoices/', include('invoices.urls')),
    path('api/v1/', include('mpesa_api.urls')),
    path('school/', include('school.urls')),
    path('shortcode/', include('shortcode.urls')),
    path('adda/', include('adda.urls')),
    path('integrations/', include('integrations.urls')),
    path('schedule/sms/', include("scheduled_sms.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scheduled_sms/urls.py
from django.urls import path
from scheduled_sms import views

app_name = "scheduled_sms"

urlpatterns = [
    path("", views.schedule_sms, name="schedule_sms"),
    path("dashboard", views.schedule_sms_dashboard, name="schedule_sms_dashboard"),
    path("sample/merged", views.scheduled_sample_merged, name="sample_merged"),
    path("list/scheduled/sms", views.list_scheduled_sms, name="list_scheduled_sms"),
    path("list/scheduled/per/month", views.list_scheduled_per_month, name="list_scheduled_per_month"),
    path("schedule/per/month", views.schedule_per_month, name="schedule_per_month"),
    path("edit/schedule/per/month/<int:id>", views.edit_schedule_per_month, name="edit_schedule_per_month"),
    path("deactivate/scheduled/per/month/<int:id>", views.deactivate_scheduled_per_month, name="deactivate_scheduled_per_month"),

    # simple
    path('simple/sms', views.simple_sms, name="simple_sms"),
    path('simple/sms/preview', views.simple_sms_preview, name='simple_sms_preview'),
    path('simple/send', views.send, name='simple_send'),

    # excel
    path('schedule/excel', views.schedule_excel, name="schedule_excel"),
    path('schedule/excel/merged', views.schedule_excel_merged, name="schedule_excel_merged"),
    path('schedule/excel/confirm', views.schedule_excel_confirm, name="schedule_excel_confirm"),

    # path('list/scheduled/messages', views.list_scheduled_messages, name="list_scheduled_messages"),
    path('list/scheduled/per/code', views.list_scheduled_per_track_code, name="list_scheduled_per_track_code"),
    path('list/scheduled/per/code', views.list_scheduled_per_track_code, name="list_scheduled_per_track_code"),
    path('disable/scheduled/per/code/<str:track_code>', views.disable_scheduled_per_track_code, name="disable_scheduled_per_track_code"),
    path('detail/scheduled/per/track_code/<str:track_code>', views.detail_scheduled_per_track_code, name="detail_scheduled_per_track_code"),
]

sms/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from sms import views
from django.contrib.auth import views as auth_views

from sms.views import OrderListJson, OrderReportJson, AllMessagesJson

app_name = 'sms'
urlpatterns = [
    # path('login', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login', views.roberms_login, name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('verify/account', views.verify_account, name='verify_account'),
    path('', views.home, name='sms-home'),
    path('profile', views.profile, name='profile'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('contact', views.contact, name='contact'),

    # customer
    path('apps', views.apps, name='apps'),
    path('send/', views.send, name='send'),
    path('simple/sms', views.simple_sms, name='simple_sms'),
    path('simple/sms/preview', views.simple_sms_preview, name='simple_sms_preview'),
    path('import/csv', views.import_csv_2, name='import_csv'),
    path('merge', views.merge_sms_2, name='merge_sms'),
    path('confirm', views.confirm, name='confirm'),
    path('customer/reports/<int:tracking_code>', views.reports, name='customer_reports'),
    path('customer/credit', views.customer_credit, name='customer_credit'),
    path('customer/contacts', views.customer_contacts, name='customer_contacts'),
    path('customer/comprehensive/reports', views.comprehensive_reports, name='comprehensive_reports'),
    path('sent/report/details/<str:track_code>', views.report_details, name='report_details'),
    path('generate/sms/report/<str:track_code>', views.generate_sms_report, name='generate_sms_report'),
    path('personalized/sms/menu', views.personalized_sms_menu, name='personalized_sms_menu'),
    path('personalized/contacts', views.personalized_from_contact_list, name='personalized_contacts'),
    # path('choose/contact/personalized/contactsgroups', views.choose_contact_groups, name='choose_contact_groups'),
    path('contact/list/sample/merged', views.c_sample_merged, name='c_sample_merged'),
    path('messages/dashboard', views.messages_dashboard, name='messages_dashboard'),

    # groups
    path('create/group', views.create_group, name='create_group'),
    path('group/contacts/<int:group_id>', views.group_contacts, name='group_contacts'),
    path('create/group/contact/<int:group_id>', views.create_contact, name='create_group_contact'),
    path('import/group/contacts/<int:group_id>', views.import_contacts, name='import_contacts'),
    path('delete/group/<int:group_id>', views.delete_group, name='delete_group'),
    path('monthly/credit/usage', views.credit_used, name='credit_usage'),
    path('delete/contacts/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('update/group/<int:group_id>', views.update_group, name='update_group'),
    path('update/contact/<int:contact_id>', views.update_contact, name='update_contact'),
    # path('delete/contact/<int:g')

    path('sms/reports', views.sms_reports, name='my_sms_reports'),
    # path('send/sms', views.send_sms, name='send_sms'),
    # path('get/sms/delivery/status', views.get_delivery_status, name='get_delivery_status'),

    #top up
    path('payment/verification', views.verify_payment, name='verify_payment'),
    path('phone-number/payment/verification', views.phone_verify_payment, name='phone_verify_payment'),
    path('register', views.register, name='register'),
    path('edit/profile', views.edit_profile, name='edit_profile'),

    # till_numbers
    path('till/numbers', views.customer_till_numbers, name='customer_till_numbers'),
    path('add/till/number', views.add_till_number, name='add_till_number'),
    path('edit/till/number/<int:till_number_id>', views.edit_till_number, name='edit_till_number'),
    path('delete/till/number/<int:till_number_id>', views.delete_till_number, name='delete_till_number'),

    #contacts
    path('activate/deactivate/contact/<int:contact_id>', views.activate_deactivate_contact, name='activate_deactivate_contact'),

    #celery
    path('contacts/upload/status/<str:task_id>', views.contacts_upload_status, name='contacts_upload_status' ),
    path('poll_contact_upload_state/<str:task_id>', views.poll_contact_upload_state, name='poll_contact_upload_state'),

    #trial
    path('get/token', views.trial, name='trial'),

    #docs
    path('documentation', views.documentation, name='documentation'),

    #sender name
    path('sender_name/applications', views.applications, name='applications'),
    path('new/sender_name/application', views.new_application, name='new_application'),
    path('application/contacts/<int:application_id>', views.application_contacts, name='application_contacts'),
    path('add/application/contact/<int:application_id>', views.add_application_contacts, name='add_application_contact'),
    path('download/application/<int:application_id>', views.show_pdf, name='show_pdf'),

    #inbox
    # path('inbox', views.inbox, name='inbox'),

    path('offers', views.offers, name='offers'),
    path('new/tag', views.new_tag, name='new_tag'),
    path('tags', views.get_tags, name='get_tags'),
    path('tag/messages/<int:tag_id>', views.tag_messages, name='tag_messages'),

    path('express/import/contacts/<int:group_id>', views.express_import_contacts, name='express_import_contacts'),

    path('clean/contacts', views.temp_clean_sys),

    #datatables
    path('my/datatable/data/<int:group_id>/', login_required(OrderListJson.as_view()), name='order_list_json'),
    path('sample/datatable/<int:group_id>', views.sample_datatable, name='sample_datatable'),

    path('draw/<str:track_code>', login_required(OrderReportJson.as_view()), name='order_report_json'),
    path('json/all/messages', login_required(AllMessagesJson.as_view()), name='all_messages_json'),

    path('my/payments', views.my_payments, name="my_payments"),
    path('add/patient', views.st_ann_add_patient, name='st_ann_add_patient'),

    # path('home/land', views.return_home_land_data)

    path('experiential/payments', views.experiential_payments, name='experiential_payments'),

    # mpesa
    path('lipa/na/mpesa/online', views.lipa_na_mpesa_online, name="lipa_na_mpesa_online")
]

sms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from sms.models import *


# class CustomerDetailsForm(forms.ModelForm):
#     class Meta:
#         model = Customer
#         fields = ('location', 'phone_number')


# class UserRegisterForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ["username", "email", "password1", "password2"]

class CustomerRegisrationForm(UserCreationForm):
    class Meta:
        model = Customer
        fields = ("username", "email", "phone_number")
        error_messages = {
            'username': {
                'unique': "A user with that email already exists.",
            },
        }


class SendForm(forms.Form):

    class Meta:
        model = Outgoing
        fields = ["phone_numbers", "text_message"]

sms/templates/sms/add_till_number.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

sms/templates/sms/credit.html
{% extends 'layouts/new_base.html' %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="row">
<div class="col-sm-12">

            <p> For Custom plan Kindly call Ronald <strong><i class="fa fa-phone"></i> 0725029795</strong></p>
            <h2> <strong> You can now get an invoice and ETR receipts for all your topups. </strong></h2>
</div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="container">
            <div class="well">
                <section id="pricing">
                    <div class="container">
                        <div class="divider">
                        </div><!--/.center-->
                        <div class="gap"></div>

                    </div>
                </section><!--/#pricing-->
                <h2> Mpesa Payment</h2>
                <hr>
            </div>
            <div class="well">
                <div class="mpesa darkerBackground">
                    <div class="instruction">
                        <ol>
                            <li>Go to M-Pesa on your mobile phone</li>
                            <li>Select Lipa na Mpesa</li>
                            <li>Select Buy Good and services</li>
                            <li>Enter Till number: <strong>9644609</strong></li>

                            <li>Enter the total<strong> amount </strong></li>
                            <li>Complete your transaction on your phone.</li>
                            <li>Wait for your confirmation SMS from M-Pesa.</li>
                            <li>Wait for your confirmation SMS from Roberms with code.</li>
                            <li>Then click on the validate payment button below and enter code</li>
                            <li style="color: darkgreen">
                                <strong>NB: Incase you do not get the verification code as indicated above, click on
                                    the validate payment button below and on the "Use phone number option", enter the phone number used to make the
                                    payment, then click the Verify button below it.
                                </strong>
                            </li>
                        </ol>
                    </div>
{#                    <div class="confirm darkerBackground">#}

{#                    </div>#}
                </div>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="container">
            <div class="well">
{#                <h2>Lipa Na M-PESA Online (STK-PUSH)</h2>#}
{#                <hr>#}
{#                <form action="{% url 'sms:lipa_na_mpesa_online' %}" method="post">#}
{#                    {% csrf_token %}#}
{#                    <div class="form-group">#}
{#                        <label>Amount (KES)</label>#}
{#                        <input type="number" name="amount" class="form-control" required>#}
{#                    </div>#}
{##}
{#                    <div class="form-group">#}
{#                        <label>Phone Number</label>#}
{#                        <input type="text" name="phone_number" class="form-control" placeholder="254111234567" required>#}
{#                        <small class="text-danger">Enter your phone number starting with 254</small>#}
{#                    </div>#}
{##}
{#                    <div class="form-group">#}
{#                        <button type="submit" class="btn btn-primary">Initiate</button>#}
{#                    </div>#}
{#                </form>#}
            </div>
        </div>
    </div>
</div>
    <hr>
    <div class="row">
    <div class="col-sm-12">
        <div class="container">
            <div class="well">
                <a style = "float: right" class="btn btn-primary verify-button" data-disable-with="Verifying" href="{% url 'sms:verify_payment' %}">Validate Payment</a>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

{% block additional_scripts %}

{% endblock %}

sms/templates/sms/customer_till_numbers.html
{% extends 'layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="row">
        <div class="col-md-12">
          <div class="tile">
            <div class="tile-title-w-btn">
              <h3 class="title">Till Numbers</h3>
              <p><a class="btn btn-primary icon-btn" href="{% url 'sms:add_till_number' %}"><i class="fa fa-plus"></i>Add Till Number</a></p>
            </div>
            <div class="tile-body">
                <table class="table table-hover table-bordered" id="sampleTable">
                    <thead>
                    <tr>
                        <th>Till Number</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for till_number in till_numbers %}
                    <tr>
                        <td>{{ till_number.till }}</td>
                        <td>
                            <a href="{% url 'sms:edit_till_number' till_number.id %}" class="btn btn-outline-primary">Edit</a>
                            <a class="btn btn-outline-danger" href="{% url 'sms:delete_till_number' till_number.id %}">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
          </div>
        </div>
</div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

sms/templates/sms/dashboard.html
{% extends 'layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
    {% comment %} <div class="col-md-12"> {% endcomment %}
       {% comment %} <div class="tile"> {% endcomment %}
{#           <div class="page-header">#}
{#               <div class="row">#}
                   {% comment %} <div class="tile-title"> {% endcomment %}

                   {% comment %} </div> {% endcomment %}
{#               </div>#}
{#           </div>#}
    <div class="row">
    <div class="col-sm-12">
        <h3>Campaigns</h3>
        <hr>
    </div>
    </div>
       <div class="row">
           <div class="col-lg-4">
           <div class="bs-component">
           <div class="card" style="-webkit-box-shadow: 0 1px 2px rgb(0 0 0 / 10%); box-shadow: 0 1px 2px rgb(0 0 0 / 10%);">
               <div class="card-header">
                   <h5 class="mb-3" id="buttons">Simple Message</h5>
               </div>
               <div class="card-body">
                   <p></p>
                   <a class="btn btn-primary" href="{% url 'sms:simple_sms' %}">Continue</a>
               </div>
           </div>
           </div>
       </div>

       <div class="col-lg-4">
           <div class="card" style="-webkit-box-shadow: 0 1px 2px rgb(0 0 0 / 10%); box-shadow: 0 1px 2px rgb(0 0 0 / 10%);">
               <div class="bs-component">
                   <div class="card-header">
                   <h5 class="mb-3" id="buttons">Personalized Messages</h5>
                   </div>
               <div class="card-body">
                   <p></p>
                   <a class="btn btn-primary" href="{% url 'sms:personalized_sms_menu' %}">Continue</a>
               </div>
               </div>
           </div>
       </div>

       <div class="col-lg-4">
           <div class="card" style="-webkit-box-shadow: 0 1px 2px rgb(0 0 0 / 10%); box-shadow: 0 1px 2px rgb(0 0 0 / 10%);">
               <div class="bs-component">
                   <div class="card-header">
                   <h5 class="mb-3" id="buttons">Schedule Messages</h5>
                   </div>
               <div class="card-body">
                   <p></p>
                   <a class="btn btn-primary" href="{%  url 'scheduled_sms:schedule_sms_dashboard' %}">Continue</a>
               </div>
               </div>
           </div>
       </div>
    </div>

    <br>

    <div class="row">

    </div>
       {% comment %} </div> {% endcomment %}
       {% comment %} </div> {% endcomment %}
{% endblock %}

{% block additional_scripts %}

{% endblock %}

sms/templates/sms/offers.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
      <link rel="icon" href="{% static 'images/robermss.ico'%}" type='image/x-icon'>
    <title>Roberms</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'digilab/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'digilab/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'digilab/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'digilab/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'digilab/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'digilab/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'digilab/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'digilab/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'digilab/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'digilab/css/style.css' %}">

  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300" class="text-black-50">


    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{%url 'sms:sms-home'%}" style="color: green" >Roberms<span></span></a>
	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav nav ml-auto">

              {% if user.is_authenticated %}

	          <li class="nav-item"><a href="#home-section" class="nav-link"><span style="color: green">Home</span></a></li>
{#            <li class="nav-item"><a href="#about-section" class="nav-link"><span>About</span></a></li>#}

{#	          <li class="nav-item"><a href="#services-section" class="nav-link"><span>Services</span></a></li>#}
	          <!-- <li class="nav-item"><a href="#projects-section" class="nav-link"><span>Projects</span></a></li> -->
	          <!-- <li class="nav-item"><a href="#testimony-section" class="nav-link"><span>Testimony</span></a></li> -->
	          <!-- <li class="nav-item"><a href="#blog-section" class="nav-link"><span>Blog</span></a></li> -->
{#	          <li class="nav-item"><a href="#contact-section" class="nav-link"><span >Contact</span></a></li>#}
            <li class="nav-item"><a href="{%url 'sms:apps'%}" class="nav-link"><span style="color: green">Dashboard</span></a></li>
            <li class="nav-item login"><a href="{%url 'sms:logout'%}" class="nav-link" style="color: green"><span>Logout</span></a></li>

            <!-- unautenticated User -->

            {% else %}

            <li class="nav-item"><a href="#home-section" class="nav-link"><span style="color: green">Home</span></a></li>
            <li class="nav-item"><a href="{%url 'sms:register'%}" class="nav-link"><span style="color: green">Sign up</span></a></li>
            <li class="nav-item login"><a href="{%url 'sms:login'%}" class="nav-link"><span style="color: green">Login</span></a></li>
              {%endif%}
	        </ul>
	      </div>
	    </div>
	  </nav>
	  <section id="home-section" class="hero">
	  	<h3 class="vr" style="color: black">Welcome to Roberms </h3>
    </section>

    <section class="ftco-section testimony-section" id="testimony-section" style="background-color:white;">
      <div class="container">
        <div class="row justify-content-center pb-3">
          <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
            <h2 class="mb-4" style="color: black">Helping businesses during covid-19</h2>
          </div>
        </div>
        <div class="row ftco-animate justify-content-center">
          <div class="col-md-12">
              <h4>Overview </h4>
              <p style="font-size: 18px; color: black">Covid 19 has made many businesses and shops closed or operating at a bare minimal. We will talk about how Roberms can help such businesses serve their customers during such periods . They include restaurants, churches,  schools and many more</p>

              <h4>Restaurants</h4>
              <p style="font-size: 18px; color: black">Roberms has come up with ways of ensuring restaurants and clubs identify, and get a way to reach  their most frequent customers. This is through their mpesa till numbers where the club can get the names and phone numbers of their clients. Periodically engage them through messages to do online delivery and inform them on offers during Covid period.</p>

              <h4>Churches </h4>
              <p style="font-size: 18px; color: black">Churches needs to communicate to their members regularly. You can collect the phone numbers of members and store them in our platform. Then when you want to broadcast anything, share the message. For instance, many churches are going live through youtube and facebook to present their sermons and anything they have. They can send links just before doing that to ensure members catch up with the events.</p>

              <h4>Schools</h4>
              <p style="font-size: 18px; color: black">With the crisis, teachers can prepare assignments and send links to the parent’s phone numbers to enable students access the learning materials posted. Some assignments can also be sent as texts and we will ensure they get to the indented users.</p>

              <h4>Shops </h4>
              <p style="font-size: 18px; color: black">Shops can utilize our sms feature to tell customers on new items than can be delivered to the clients. For instance, many businesses have shifted their lines to help in curbing the spread of covid 19. They will inform clients what they can offer i.e masks, sanitizers and help.</p>

              <p style="font-size: 18px; color: black">Above all, everybody can help spread the message of hope and how to curb the spread through messages. </p>
              <p style="font-size: 18px; color: black" >Wash your hands regularly.</p>
              <p style="font-size: 18px; color: black">Stay home </p>
          </div>
        </div>
      </div>
    </section>


  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'digilab/js/jquery.min.js' %}"></script>
  <script src="{% static 'digilab/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'digilab/js/popper.min.js' %}"></script>
  <script src="{% static 'digilab/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'digilab/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'digilab/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'digilab/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'digilab/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'digilab/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'digilab/js/aos.js' %}"></script>
  <script src="{% static 'digilab/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'digilab/js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'digilab/js/google-map.js' %}"></script>
  <script src="{% static 'digilab/js/main.js' %}"></script>

  </body>
</html>

sms/templates/sms/personalized_sms_menu.html
{% extends 'layouts/new_base.html' %}
{% load static %}

{% block additional_styles %}
    {#<link rel="stylesheet" href="{% static 'css/custom.css' %}">#}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-sm-12">
            <h3>Personalized Messages</h3>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="bs-component">
                <div class="card" style="-webkit-box-shadow: 0 1px 2px rgb(0 0 0 / 10%); box-shadow: 0 1px 2px rgb(0 0 0 / 10%);">
                    <div class="card-header">
                        <h5 class="mb-3" id="buttons">Send Personalized Message To Existing Contact Group</h5>
                    </div>
                    <div class="card-body">
                        <p>Send personalized message to clients stored in your contact <br>
                            groups</p>
                        <a class="btn btn-sm btn btn-primary" style="color: white" href="{% url 'sms:personalized_contacts' %}">Continue</a>
                        <br>
                        <small>Dont have contacts, Click<a href="{% url 'sms:customer_contacts' %}"> Here</a> to
                            add</small>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="card" style="-webkit-box-shadow: 0 1px 2px rgb(0 0 0 / 10%); box-shadow: 0 1px 2px rgb(0 0 0 / 10%);">
                <div class="bs-component">
                    <div class="card-header">
                        <h5 class="mb-3" id="buttons">Send Personalized SMS from a File</h5>
                    </div>
                    <div class="card-body">
                        <p>Already storing information on your customers? Upload this information from an Excel or CSV
                            file and send personalised messages unique to each recipient.</p>
                        <br>
                        <a class="btn btn-sm btn btn-primary" style="color: white" href="{% url 'sms:import_csv' %}">Continue</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

sms/templates/sms/result.html
{% extends 'layouts/new_base.html' %}

{% block content %}
{{ data }}
{% endblock %}

{% block additional_scripts %}

{% endblock %}