roberms/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views, views

from roberms import settings


urlpatterns = [
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(
        template_name='r/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='r/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='r/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='r/password_reset_complete.html'), name='password_reset_complete'),
    # url('^', include('django.contrib.auth.urls')),


    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('roberms/super/admin/', admin.site.urls),

    path('', include('sms.urls')),
    path('sms/v1/', include('sms_api.urls')),
    path('roberms/admin/', include('roberms_admin.urls')),
    path('roberms/salesperson/', include('salesperson.urls')),
    path('invoices/', include('invoices.urls')),
    path('api/v1/', include('mpesa_api.urls')),
    path('school/', include('school.urls')),
    path('shortcode/', include('shortcode.urls')),
    path('adda/', include('adda.urls')),
    path('integrations/', include('integrations.urls')),
    path('schedule/sms/', include("scheduled_sms.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.urls import path

from school import views

app_name = 'School'
urlpatterns = [
    path('home', views.home, name='home'),
    path('register', views.school_register, name='register'),
    path('login', views.school_login, name='login'),
    path('logout', views.school_logout, name='logout'),
    path('students/<int:stream_id>', views.school_students, name='school_students'),
    path('streams/<int:form_id>', views.school_streams, name='school_streams'),
    path('classes', views.school_classes, name='school_classes'),
    path('add_class', views.add_class, name='add_class'),
    path('edit_class/<int:class_id>', views.edit_class, name='edit_class'),
    path('add/stream/<int:class_id>', views.add_stream, name='add_stream'),
    path('edit/stream/<int:stream_id>', views.edit_stream, name='edit_stream'),
    path('add_student/<int:stream_id>', views.add_student, name='add_student'),
    # path('edit_student/<int:student_id>', vie/school/add/exam/ws.edit_student, name='edit_student'),
    path('add/guardian/<int:stream_id>', views.add_guardian, name='add_guardian'),
    path('add/term/<int:form_id>', views.add_term, name='add_term'),
    path('add/exam/<int:form_id>/<int:term_year_id>', views.add_exam, name='add_exam'),

    #examinations
    path('exam/classes', views.examination_classes, name='examination_classes'),
    path('exam/terms/<int:form_id>', views.examination_terms, name='examination_terms'),
    path('exam/exams/<int:term_year_id>/<int:form_id>', views.examinations_exam, name='examinations_exam'),
    path('exam/students/<int:form_id>/<int:exam_id>', views.examination_students, name='examination_students'),
    path('exam/subject/score/<int:student_id>/<int:exam_id>/<int:form_id>', views.student_subject_scores, name='student_subject_scores'),
    path('edit_student_score/<int:student_id>/<int:exam_id>/<int:subject_id>', views.edit_subject_score, name='edit_student_score'),
    path('final/score/<int:student_id>/<int:exam_id>', views.grade_student, name='grade_student'),
    #finance
    path('finance/classes', views.finance_classes, name='finance_classes'),
    path('finance/students/<int:class_id>', views.finance_students, name='finance_students'),
    path('finance/student/payments/<int:student_id>/<int:term_id>/<int:form_id>', views.finance_student_payments, name='finance_student_payments'),
    path('finance/student/add/payment/<int:student_id>/<int:term_id>/<int:form_id>', views.finance_add_payment, name='finance_add_payment'),
    path('payment/receipt/<int:student_fee_id>', views.payment_receipt_preview, name='payment_receipt_preview'),

    path('finance/years', views.finance_years, name='finance_years'),
    path('finance/term/years/<int:term_id>', views.school_term_years, name='school_term_years'),
    path('set_term_fee/<int:term_year_id>/<int:form_id>', views.set_term_fee, name='set_term_fee'),
    path('finance_classes/<int:term_year_id>', views.school_finance_classes, name='finance_classes'),
    path('add_fee_break_down/<int:term_year_id>', views.add_fee_break_down, name='add_fee_break_down'),

    path('finance_year_classes/<int:year>', views.finance_year_classes, name='finance_year_classes'),
    path('finance_terms/<int:form_id>/<int:year>', views.finance_terms, name='finance_terms'),

    #sms
    path('sms/menu', views.sms_menu, name='sms_menu'),
    path('personalized_sms_menu', views.personalized_sms_menu, name='personalized_sms_menu'),
    path('simple_sms', views.simple_sms, name='simple_sms'),
    path('personalized_from_file', views.personalized_from_file, name='personalized_from_file'),
    path('personalized_from_contact_group', views.personalized_from_contact_group, name='personalized_from_contact_group'),

    #reports
    path('generate_exam_results/<int:exam_id>', views.generate_exam_results, name='generate_exam_results_template'),

    # deletions
    path('delete_stream/<int:stream_id>', views.delete_stream, name='delete_stream'),
    path('delete_student/<int:student_id>', views.delete_student, name='delete_student'),
    path('delete_class', views.delete_class, name='delete_class'),

    #template
    path('exam/results/template/<int:exam_id>', views.download_exam_template, name='exam_results_template'),
    path('upload/exam/results/<int:exam_id>', views.upload_student_marks, name='upload_student_marks'),

    #settings
    path('settings', views.settings, name='settings'),
    path('term/years/<int:term_id>', views.term_years, name='term_years'),

    #new exams
    path('exam/years', views.exam_years, name='exam_years'),
    path('exam/forms/<int:year>', views.forms_by_year, name='forms_by_year'),
    path('exam/terms/<int:year>/<int:form_id>', views.exam_terms_by_year, name='exam_terms_by_year'),
]

sms/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from sms import views
from django.contrib.auth import views as auth_views

from sms.views import OrderListJson, OrderReportJson, AllMessagesJson

app_name = 'sms'
urlpatterns = [
    # path('login', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login', views.roberms_login, name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('verify/account', views.verify_account, name='verify_account'),
    path('', views.home, name='sms-home'),
    path('profile', views.profile, name='profile'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('contact', views.contact, name='contact'),

    # customer
    path('apps', views.apps, name='apps'),
    path('send/', views.send, name='send'),
    path('simple/sms', views.simple_sms, name='simple_sms'),
    path('simple/sms/preview', views.simple_sms_preview, name='simple_sms_preview'),
    path('import/csv', views.import_csv_2, name='import_csv'),
    path('merge', views.merge_sms_2, name='merge_sms'),
    path('confirm', views.confirm, name='confirm'),
    path('customer/reports/<int:tracking_code>', views.reports, name='customer_reports'),
    path('customer/credit', views.customer_credit, name='customer_credit'),
    path('customer/contacts', views.customer_contacts, name='customer_contacts'),
    path('customer/comprehensive/reports', views.comprehensive_reports, name='comprehensive_reports'),
    path('sent/report/details/<str:track_code>', views.report_details, name='report_details'),
    path('generate/sms/report/<str:track_code>', views.generate_sms_report, name='generate_sms_report'),
    path('personalized/sms/menu', views.personalized_sms_menu, name='personalized_sms_menu'),
    path('personalized/contacts', views.personalized_from_contact_list, name='personalized_contacts'),
    # path('choose/contact/personalized/contactsgroups', views.choose_contact_groups, name='choose_contact_groups'),
    path('contact/list/sample/merged', views.c_sample_merged, name='c_sample_merged'),
    path('messages/dashboard', views.messages_dashboard, name='messages_dashboard'),

    # groups
    path('create/group', views.create_group, name='create_group'),
    path('group/contacts/<int:group_id>', views.group_contacts, name='group_contacts'),
    path('create/group/contact/<int:group_id>', views.create_contact, name='create_group_contact'),
    path('import/group/contacts/<int:group_id>', views.import_contacts, name='import_contacts'),
    path('delete/group/<int:group_id>', views.delete_group, name='delete_group'),
    path('monthly/credit/usage', views.credit_used, name='credit_usage'),
    path('delete/contacts/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('update/group/<int:group_id>', views.update_group, name='update_group'),
    path('update/contact/<int:contact_id>', views.update_contact, name='update_contact'),
    # path('delete/contact/<int:g')

    path('sms/reports', views.sms_reports, name='my_sms_reports'),
    # path('send/sms', views.send_sms, name='send_sms'),
    # path('get/sms/delivery/status', views.get_delivery_status, name='get_delivery_status'),

    #top up
    path('payment/verification', views.verify_payment, name='verify_payment'),
    path('phone-number/payment/verification', views.phone_verify_payment, name='phone_verify_payment'),
    path('register', views.register, name='register'),
    path('edit/profile', views.edit_profile, name='edit_profile'),

    # till_numbers
    path('till/numbers', views.customer_till_numbers, name='customer_till_numbers'),
    path('add/till/number', views.add_till_number, name='add_till_number'),
    path('edit/till/number/<int:till_number_id>', views.edit_till_number, name='edit_till_number'),
    path('delete/till/number/<int:till_number_id>', views.delete_till_number, name='delete_till_number'),

    #contacts
    path('activate/deactivate/contact/<int:contact_id>', views.activate_deactivate_contact, name='activate_deactivate_contact'),

    #celery
    path('contacts/upload/status/<str:task_id>', views.contacts_upload_status, name='contacts_upload_status' ),
    path('poll_contact_upload_state/<str:task_id>', views.poll_contact_upload_state, name='poll_contact_upload_state'),

    #trial
    path('get/token', views.trial, name='trial'),

    #docs
    path('documentation', views.documentation, name='documentation'),

    #sender name
    path('sender_name/applications', views.applications, name='applications'),
    path('new/sender_name/application', views.new_application, name='new_application'),
    path('application/contacts/<int:application_id>', views.application_contacts, name='application_contacts'),
    path('add/application/contact/<int:application_id>', views.add_application_contacts, name='add_application_contact'),
    path('download/application/<int:application_id>', views.show_pdf, name='show_pdf'),

    #inbox
    # path('inbox', views.inbox, name='inbox'),

    path('offers', views.offers, name='offers'),
    path('new/tag', views.new_tag, name='new_tag'),
    path('tags', views.get_tags, name='get_tags'),
    path('tag/messages/<int:tag_id>', views.tag_messages, name='tag_messages'),

    path('express/import/contacts/<int:group_id>', views.express_import_contacts, name='express_import_contacts'),

    path('clean/contacts', views.temp_clean_sys),

    #datatables
    path('my/datatable/data/<int:group_id>/', login_required(OrderListJson.as_view()), name='order_list_json'),
    path('sample/datatable/<int:group_id>', views.sample_datatable, name='sample_datatable'),

    path('draw/<str:track_code>', login_required(OrderReportJson.as_view()), name='order_report_json'),
    path('json/all/messages', login_required(AllMessagesJson.as_view()), name='all_messages_json'),

    path('my/payments', views.my_payments, name="my_payments"),
    path('add/patient', views.st_ann_add_patient, name='st_ann_add_patient'),

    # path('home/land', views.return_home_land_data)

    path('experiential/payments', views.experiential_payments, name='experiential_payments'),

    # mpesa
    path('lipa/na/mpesa/online', views.lipa_na_mpesa_online, name="lipa_na_mpesa_online")
]

school/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import formset_factory

from school.models import *


class SchoolAdminForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.required:
            self.fields[field].required = False

    class Meta:
        model = SchoolAdmin
        fields = ("username", "email", "password1", "password2", "phone_number", "school",)
        required = ("school",)


class SchoolForm(forms.ModelForm):
    class Meta:
        model = School
        fields = ("name", "address", "location", "school_type",)


class FeeForm(forms.ModelForm):
    class Meta:
        model = FeeBreakDown
        fields = ("name", "percentage", "term_year")

school/templates/school/finance/add_fee_break_down.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}
{% load school_filters %}
{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <h3> Fee Break Down </h3>
    <hr>
</div>

<div class="row">
    <div class="col-sm-3">

    </div>

    <div class="col-sm-6">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Break Down Name</label>
                <input type="text" class="form-control" id="name" name="name">
            </div>

            <div class="form-group">
                <label for="percentage">Percentage</label>
                <input type="text" class="form-control" name="percentage" id="percentage">
            </div>

            <div class="form-group">
                <label for="term_year">Term Year</label>
                <input type="text" value="{{ term_year.id }}" class="form-control" id="term_year" name="term_year">
            </div>
            <input type="submit" class="btn btn-sm btn-outline-success" value="Submit">
        </form>
    </div>

</div>
</div>

    <div class="col-sm-3">

    </div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

school/templates/school/finance/add_payment.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <h4>Add Payment</h4>
    <hr>
</div>
<div class="col-sm-6">
    <form class="form-group" action="{% url 'School:finance_add_payment' student_id term_id form_id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label>Payment Date</label>
            <input type="date" class="form-control" name="date_paid">
        </div>

        <div class="form-group" >
            <label>Amount</label>
            <input type="text" class="form-control" name="amount_paid">
        </div>

        <button type="submit" class="btn btn-primary">Add Payment</button>
    </form>
</div>
</div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

school/templates/school/finance/classes.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}
{% load school_filters %}
{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h3>Classes</h3>
        </div>
        <div class="col-sm-6">
{#            <a class="btn btn-primary pull-right flex-column text-white" href="{% url 'School:finance_add_payment' student_id form_id term_id %}">Add Payment</a>#}
        </div>
    </div>
    <hr>

</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Form Name</th>
{#                    <th>Fee</th>#}
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for form in forms %}
                <tr>
                    <td><a href="">{{ form.name }}</a></td>
                    <td>
                        <a href="{% url 'School:set_term_fee' term_year.id   form.id  %}" class="btn btn-sm btn-outline-success">Set Fee</a>
                        <a href="" class="btn btn-sm btn-outline-success">Set Fee BreakDown</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

school/templates/school/finance/fee_break_down.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}
{% load school_filters %}
{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h3>Fee Break Down</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-primary float-right flex-column text-white" href="{% url 'School:add_fee_break_down' term_year.id %}">Add Fee Break Down</a>
        </div>
    </div>
    <hr>

</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Break Down Item</th>
                    <th>Percentage</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for fee_break_down in fee_break_downs %}
                <tr>
                    <td><a href="">{{ fee_break_down.name }}</a></td>
                    <td>{{ fee_break_down.percentage }}</td>
                    <td>
                        <a href="" class="btn btn-sm btn-outline-success">Edit</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

school/templates/school/finance/finance_classes.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h3>Classes</h3>
        </div>
        <div class="col-sm-6">
{#            <a class="btn btn-primary pull-right flex-column text-white" href="{% url 'School:add_class' %}">Add Class</a>#}
        </div>
    </div>
    <hr>

</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Form Name</th>
                    <th>Streams</th>
{#                    <th>Actions</th>#}
                </tr>
                </thead>
                <tbody>
                {% for class in classes %}
                <tr>
                    <td><a href="{% url 'School:finance_students' class.id %}">{{ class.name }}</a></td>
                    <td>0</td>
{#                    <td>#}
{#                        <a href="{% url 'School:edit_class' class.id %}" class="btn btn-outline-primary">Edit</a>#}
{#                        <a class="btn btn-outline-danger">Delete</a>#}
{#                    </td>#}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

school/templates/school/finance/finance_student_payments.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h3>Payments</h3>
        </div>
         <div class="col-sm-6">
            <a class="btn btn-primary pull-right flex-column text-white" href="{% url 'School:finance_add_payment' student_id term_id form_id %}">Add Payment</a>
        </div>
    </div>
    <hr>

</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Payment Date</th>
                    <th>Amount</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for payment in payments %}
                <tr>
                    <td><a href="">{{ payment.date_paid }}</a></td>
                    <td>{{ payment.amount_paid }}</td>
                    <td>
                        <a href="{% url 'School:payment_receipt_preview' payment.id %}" class="btn btn-outline-primary">Print Receipt</a>
                        <a href="" class="btn btn-outline-primary">Edit</a>
                        <a class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

school/templates/school/finance/finance_students.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}
{% load school_filters %}
{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h3>Students</h3>
        </div>
        <div class="col-sm-6">
{#            <a class="btn btn-primary pull-right flex-column text-white" href="{% url 'School:finance_add_payment' student_id form_id term_id %}">Add Payment</a>#}
        </div>
    </div>
    <hr>

</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Student Name</th>
                    <th>Gender</th>
                    <th>Admission Number</th>
                    <th>Fee Balance</th>
{#                    <th>Actions</th>#}
                </tr>
                </thead>
                <tbody>
                {% for student in students %}
                <tr>
                    <td><a href="{% url 'School:finance_student_payments' student.id student.id|term_id class_id  %}">{{ student.first_name }} {{ student.last_name }}</a></td>
                    <td>{{ student.gender }}</td>
                    <td>{{ student.admission_number }}</td>
                    <td>{{ student.id|term_id|get_list:class_id|get_fee_balance:student.id }}</td>
{#                    <td>#}
{#                        <a href="" class="btn btn-outline-primary">Edit</a>#}
{#                        <a class="btn btn-outline-danger">Delete</a>#}
{#                    </td>#}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

school/templates/school/finance/school_classes.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}
{% load school_filters %}
{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h3>Classes</h3>
        </div>
        <div class="col-sm-6">
{#            <a class="btn btn-primary pull-right flex-column text-white" href="{% url 'School:finance_add_payment' student_id form_id term_id %}">Add Payment</a>#}
        </div>
    </div>
    <hr>

</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Form Name</th>
{#                    <th>Fee</th>#}
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for form in classes %}
                <tr>
                    <td><a href="{% url 'School:finance_terms' form.id year %}">{{ form.name }}</a></td>
                    <td>
{#                        <a href="{% url 'School:set_term_fee' term_year.id   form.id  %}" class="btn btn-sm btn-outline-success">Set Fee</a>#}
{#                        <a href="" class="btn btn-sm btn-outline-success">Set Fee BreakDown</a>#}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

school/templates/school/finance/school_years.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h3>Years</h3>
        </div>
        <div class="col-sm-6">
{#            <a class="btn btn-primary pull-right flex-column text-white" href="{% url 'School:add_term' form_id %}">Add Term</a>#}
        </div>
    </div>
    <hr>

</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Year</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for year in years %}
                <tr>
                    <td><a href="{% url 'School:finance_year_classes' year %}">{{ year }}</a></td>
                    <td>
                        Coming Soon
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

school/templates/school/finance/set_term_fee.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}
{% load school_filters %}
{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <h4>Set Term Fee</h4>
    <hr>
</div>
<div class="col-sm-6">
    <form class="form-group" action="{% url 'School:set_term_fee' term_year.id form.id %}" method="POST">
        {% csrf_token %}

        <div class="form-group">
            <label>Amount</label>
            {% if fee is not None %}
                <input type="number" value="{{ fee.fee }}" class="form-control" name="fee">
            {% else %}
                <input type="number" class="form-control" name="fee">
            {% endif %}
        </div>

        <div class="form-group" hidden>
            <label>Term Year</label>
            <input type="text" value="{{ term_year.id }}" class="form-control" name="term_year">
        </div>

        <div class="form-group" hidden >
            <label>Form</label>
            <input type="text" value="{{ form.id }}" class="form-control" name="form">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
</div>
{% endblock %}

school/templates/school/finance/terms.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}
{% load school_filters %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h3>Terms</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-primary float-right flex-column text-white" href="{% url 'School:add_term' form_id %}">Add Term</a>
        </div>
    </div>
    <hr>

</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Term Name</th>
                    <th>Year</th>
                    <th>Fee</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for term in terms %}
                <tr>
                    <td><a href="{% url 'School:examinations_exam' term.id|term_year_id:year form_id %}">{{ term.name }}</a></td>
                    <td>{{ year }}</td>
                    <td>{{ term.fee }}</td>
                    <td>
{#                        <a href="" class="btn btn-outline-primary">Edit</a>#}
{#                        <a class="btn btn-outline-danger">Delete</a>#}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

school/templates/school/finance/view_fee.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}
{% load school_filters %}
{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}

{% endblock %}

school/templates/school/finance/years.html
{% extends 'school/layouts/new_base.html' %}
{% load static %}
{% load school_filters %}
{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h3>Years</h3>
        </div>
        <div class="col-sm-6">
{#            <a class="btn btn-primary pull-right flex-column text-white" href="{% url 'School:finance_add_payment' student_id form_id term_id %}">Add Payment</a>#}
        </div>
    </div>
    <hr>

</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Year</th>
{#                    <th>Fee</th>#}
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for term_year in term_years %}
                <tr>
                    <td><a href="{% url 'School:finance_classes' term_year.id %}">{{ term_year.date.year }}</a></td>
                    <td>Coming Soon</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}