roberms/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views, views

from roberms import settings


urlpatterns = [
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(
        template_name='r/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='r/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='r/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='r/password_reset_complete.html'), name='password_reset_complete'),
    # url('^', include('django.contrib.auth.urls')),


    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('roberms/super/admin/', admin.site.urls),

    path('', include('sms.urls')),
    path('sms/v1/', include('sms_api.urls')),
    path('roberms/admin/', include('roberms_admin.urls')),
    path('roberms/salesperson/', include('salesperson.urls')),
    path('invoices/', include('invoices.urls')),
    path('api/v1/', include('mpesa_api.urls')),
    path('school/', include('school.urls')),
    path('shortcode/', include('shortcode.urls')),
    path('adda/', include('adda.urls')),
    path('integrations/', include('integrations.urls')),
    path('schedule/sms/', include("scheduled_sms.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salesperson/urls.py
from django.urls import path
from salesperson import views

app_name = 'salesperson'
urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('clients', views.clients, name='clients'),
    path('client/top/ups/<int:client_id>', views.client_top_ups, name='client_top_ups'),
    path('top_ups', views.all_top_ups, name='all_top_ups'),
    path('account/usage', views.account_usage, name='account_usage'),
    path('logout', views.sales_logout, name='sales_logout'),
    # path('/add/client', views.add_client, name='add_client')
    # path('/sales_people', views.sales_people, name='sales_people'),
    # path('/add_sales_person', views.add_sales_person, name='add_sales_person')

    path('my/companies', views.my_companies, name='my_companies'),
    path('company/appointments/<int:company_id>', views.appointment_list, name='company_appointments'),
    path('add/company', views.add_company, name='add_company'),
    path('edit/company/<int:company_id>', views.edit_company, name='edit_company'),
    path('add/appointment/<int:company_id>', views.add_appointment, name='add_appointment'),
    path('edit/appointment/<int:appointment_id>', views.edit_appointment, name='edit_appointment'),

    path('mark_visited_not_visited/<int:appointment_id>', views.mark_visited_not_visited, name='mark_visited_not_visited'),
]

school/urls.py
from django.urls import path

from school import views

app_name = 'School'
urlpatterns = [
    path('home', views.home, name='home'),
    path('register', views.school_register, name='register'),
    path('login', views.school_login, name='login'),
    path('logout', views.school_logout, name='logout'),
    path('students/<int:stream_id>', views.school_students, name='school_students'),
    path('streams/<int:form_id>', views.school_streams, name='school_streams'),
    path('classes', views.school_classes, name='school_classes'),
    path('add_class', views.add_class, name='add_class'),
    path('edit_class/<int:class_id>', views.edit_class, name='edit_class'),
    path('add/stream/<int:class_id>', views.add_stream, name='add_stream'),
    path('edit/stream/<int:stream_id>', views.edit_stream, name='edit_stream'),
    path('add_student/<int:stream_id>', views.add_student, name='add_student'),
    # path('edit_student/<int:student_id>', vie/school/add/exam/ws.edit_student, name='edit_student'),
    path('add/guardian/<int:stream_id>', views.add_guardian, name='add_guardian'),
    path('add/term/<int:form_id>', views.add_term, name='add_term'),
    path('add/exam/<int:form_id>/<int:term_year_id>', views.add_exam, name='add_exam'),

    #examinations
    path('exam/classes', views.examination_classes, name='examination_classes'),
    path('exam/terms/<int:form_id>', views.examination_terms, name='examination_terms'),
    path('exam/exams/<int:term_year_id>/<int:form_id>', views.examinations_exam, name='examinations_exam'),
    path('exam/students/<int:form_id>/<int:exam_id>', views.examination_students, name='examination_students'),
    path('exam/subject/score/<int:student_id>/<int:exam_id>/<int:form_id>', views.student_subject_scores, name='student_subject_scores'),
    path('edit_student_score/<int:student_id>/<int:exam_id>/<int:subject_id>', views.edit_subject_score, name='edit_student_score'),
    path('final/score/<int:student_id>/<int:exam_id>', views.grade_student, name='grade_student'),
    #finance
    path('finance/classes', views.finance_classes, name='finance_classes'),
    path('finance/students/<int:class_id>', views.finance_students, name='finance_students'),
    path('finance/student/payments/<int:student_id>/<int:term_id>/<int:form_id>', views.finance_student_payments, name='finance_student_payments'),
    path('finance/student/add/payment/<int:student_id>/<int:term_id>/<int:form_id>', views.finance_add_payment, name='finance_add_payment'),
    path('payment/receipt/<int:student_fee_id>', views.payment_receipt_preview, name='payment_receipt_preview'),

    path('finance/years', views.finance_years, name='finance_years'),
    path('finance/term/years/<int:term_id>', views.school_term_years, name='school_term_years'),
    path('set_term_fee/<int:term_year_id>/<int:form_id>', views.set_term_fee, name='set_term_fee'),
    path('finance_classes/<int:term_year_id>', views.school_finance_classes, name='finance_classes'),
    path('add_fee_break_down/<int:term_year_id>', views.add_fee_break_down, name='add_fee_break_down'),

    path('finance_year_classes/<int:year>', views.finance_year_classes, name='finance_year_classes'),
    path('finance_terms/<int:form_id>/<int:year>', views.finance_terms, name='finance_terms'),

    #sms
    path('sms/menu', views.sms_menu, name='sms_menu'),
    path('personalized_sms_menu', views.personalized_sms_menu, name='personalized_sms_menu'),
    path('simple_sms', views.simple_sms, name='simple_sms'),
    path('personalized_from_file', views.personalized_from_file, name='personalized_from_file'),
    path('personalized_from_contact_group', views.personalized_from_contact_group, name='personalized_from_contact_group'),

    #reports
    path('generate_exam_results/<int:exam_id>', views.generate_exam_results, name='generate_exam_results_template'),

    # deletions
    path('delete_stream/<int:stream_id>', views.delete_stream, name='delete_stream'),
    path('delete_student/<int:student_id>', views.delete_student, name='delete_student'),
    path('delete_class', views.delete_class, name='delete_class'),

    #template
    path('exam/results/template/<int:exam_id>', views.download_exam_template, name='exam_results_template'),
    path('upload/exam/results/<int:exam_id>', views.upload_student_marks, name='upload_student_marks'),

    #settings
    path('settings', views.settings, name='settings'),
    path('term/years/<int:term_id>', views.term_years, name='term_years'),

    #new exams
    path('exam/years', views.exam_years, name='exam_years'),
    path('exam/forms/<int:year>', views.forms_by_year, name='forms_by_year'),
    path('exam/terms/<int:year>/<int:form_id>', views.exam_terms_by_year, name='exam_terms_by_year'),
]

sms/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from sms import views
from django.contrib.auth import views as auth_views

from sms.views import OrderListJson, OrderReportJson, AllMessagesJson

app_name = 'sms'
urlpatterns = [
    # path('login', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login', views.roberms_login, name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('verify/account', views.verify_account, name='verify_account'),
    path('', views.home, name='sms-home'),
    path('profile', views.profile, name='profile'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('contact', views.contact, name='contact'),

    # customer
    path('apps', views.apps, name='apps'),
    path('send/', views.send, name='send'),
    path('simple/sms', views.simple_sms, name='simple_sms'),
    path('simple/sms/preview', views.simple_sms_preview, name='simple_sms_preview'),
    path('import/csv', views.import_csv_2, name='import_csv'),
    path('merge', views.merge_sms_2, name='merge_sms'),
    path('confirm', views.confirm, name='confirm'),
    path('customer/reports/<int:tracking_code>', views.reports, name='customer_reports'),
    path('customer/credit', views.customer_credit, name='customer_credit'),
    path('customer/contacts', views.customer_contacts, name='customer_contacts'),
    path('customer/comprehensive/reports', views.comprehensive_reports, name='comprehensive_reports'),
    path('sent/report/details/<str:track_code>', views.report_details, name='report_details'),
    path('generate/sms/report/<str:track_code>', views.generate_sms_report, name='generate_sms_report'),
    path('personalized/sms/menu', views.personalized_sms_menu, name='personalized_sms_menu'),
    path('personalized/contacts', views.personalized_from_contact_list, name='personalized_contacts'),
    # path('choose/contact/personalized/contactsgroups', views.choose_contact_groups, name='choose_contact_groups'),
    path('contact/list/sample/merged', views.c_sample_merged, name='c_sample_merged'),
    path('messages/dashboard', views.messages_dashboard, name='messages_dashboard'),

    # groups
    path('create/group', views.create_group, name='create_group'),
    path('group/contacts/<int:group_id>', views.group_contacts, name='group_contacts'),
    path('create/group/contact/<int:group_id>', views.create_contact, name='create_group_contact'),
    path('import/group/contacts/<int:group_id>', views.import_contacts, name='import_contacts'),
    path('delete/group/<int:group_id>', views.delete_group, name='delete_group'),
    path('monthly/credit/usage', views.credit_used, name='credit_usage'),
    path('delete/contacts/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('update/group/<int:group_id>', views.update_group, name='update_group'),
    path('update/contact/<int:contact_id>', views.update_contact, name='update_contact'),
    # path('delete/contact/<int:g')

    path('sms/reports', views.sms_reports, name='my_sms_reports'),
    # path('send/sms', views.send_sms, name='send_sms'),
    # path('get/sms/delivery/status', views.get_delivery_status, name='get_delivery_status'),

    #top up
    path('payment/verification', views.verify_payment, name='verify_payment'),
    path('phone-number/payment/verification', views.phone_verify_payment, name='phone_verify_payment'),
    path('register', views.register, name='register'),
    path('edit/profile', views.edit_profile, name='edit_profile'),

    # till_numbers
    path('till/numbers', views.customer_till_numbers, name='customer_till_numbers'),
    path('add/till/number', views.add_till_number, name='add_till_number'),
    path('edit/till/number/<int:till_number_id>', views.edit_till_number, name='edit_till_number'),
    path('delete/till/number/<int:till_number_id>', views.delete_till_number, name='delete_till_number'),

    #contacts
    path('activate/deactivate/contact/<int:contact_id>', views.activate_deactivate_contact, name='activate_deactivate_contact'),

    #celery
    path('contacts/upload/status/<str:task_id>', views.contacts_upload_status, name='contacts_upload_status' ),
    path('poll_contact_upload_state/<str:task_id>', views.poll_contact_upload_state, name='poll_contact_upload_state'),

    #trial
    path('get/token', views.trial, name='trial'),

    #docs
    path('documentation', views.documentation, name='documentation'),

    #sender name
    path('sender_name/applications', views.applications, name='applications'),
    path('new/sender_name/application', views.new_application, name='new_application'),
    path('application/contacts/<int:application_id>', views.application_contacts, name='application_contacts'),
    path('add/application/contact/<int:application_id>', views.add_application_contacts, name='add_application_contact'),
    path('download/application/<int:application_id>', views.show_pdf, name='show_pdf'),

    #inbox
    # path('inbox', views.inbox, name='inbox'),

    path('offers', views.offers, name='offers'),
    path('new/tag', views.new_tag, name='new_tag'),
    path('tags', views.get_tags, name='get_tags'),
    path('tag/messages/<int:tag_id>', views.tag_messages, name='tag_messages'),

    path('express/import/contacts/<int:group_id>', views.express_import_contacts, name='express_import_contacts'),

    path('clean/contacts', views.temp_clean_sys),

    #datatables
    path('my/datatable/data/<int:group_id>/', login_required(OrderListJson.as_view()), name='order_list_json'),
    path('sample/datatable/<int:group_id>', views.sample_datatable, name='sample_datatable'),

    path('draw/<str:track_code>', login_required(OrderReportJson.as_view()), name='order_report_json'),
    path('json/all/messages', login_required(AllMessagesJson.as_view()), name='all_messages_json'),

    path('my/payments', views.my_payments, name="my_payments"),
    path('add/patient', views.st_ann_add_patient, name='st_ann_add_patient'),

    # path('home/land', views.return_home_land_data)

    path('experiential/payments', views.experiential_payments, name='experiential_payments'),

    # mpesa
    path('lipa/na/mpesa/online', views.lipa_na_mpesa_online, name="lipa_na_mpesa_online")
]

salesperson/models.py
from django.db import models

# Create your models here.

salesperson/forms.py
from django import forms
from roberms_admin.models import Company


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'phone_number', 'contact_person',
                  'email', 'sales_person', 'location')

salesperson/templates/sales_layouts/new_base.html
<!DOCTYPE html>
{% load static %}
{% load filters %}
<html lang="en">
  <head>  <link rel="icon" href="{% static 'images/robermss.ico'%}" type='image/x-icon'>
  {% block additional_meta %}

  {% endblock %}
    <title>Roberms</title>
    <link rel='stylesheet' type='text/css' href='{% static 'css/main.css' %}'>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="{% static 'css/custom.css' %}">
      <style>
          .alert {
            position: relative;
            padding: 0.1rem 1.25rem;
            margin-bottom: 1rem;
            border: 2px solid transparent;
            border-radius: 1.25rem;
            }
          .alert-dismissible .close {
            position: absolute;
            top: 0;
            right: 0;
            padding: 0.1rem 1.25rem;
            color: inherit;
            }
      </style>
      {% block additional_styles %}

      {% endblock %}
  </head>
  <body class="app sidebar-mini rtl">
    <!-- Navbar-->
    {% include 'sales_layouts/new_top_nav.html' %}
    <!-- Sidebar menu-->
    {% include 'sales_layouts/side_nav.html' %}

    <main class="app-content">
    <div class="app-title">

        <div class="row col-sm-12">
        <div class="col-lg-3">
            <p>Welcome,<strong>  </strong></p>
        </div>
        <div class="col-lg-6">
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-dismissible {% if message.tags == 'error' %} alert-danger {% else %} alert-primary {% endif %}">
                    <button class="close" type="button" data-dismiss="alert">×</button><strong></strong><a class="alert-link" href="#">{{ message }}</a>
                </div>
            {% endfor %}
            {% endif %}
        </div>

        <div class="col-lg-3">
            <ul class="app-breadcrumb breadcrumb">
              <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
              <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            </ul>
        </div>

        </div>
      </div>

    {% block content %}

  {% endblock %}
{#    </div>#}
    </main>



    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/chart.js' %}"></script>

    <!-- Data table plugin-->
    <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
    {% block additional_scripts %}

    {% endblock %}

  </body>
</html>

salesperson/templates/sales_layouts/new_top_nav.html
{% load sales_person_filters %}
<header class="app-header"><a class="app-header__logo" href="{% url 'salesperson:dashboard'%}">ROBERMS</a>
      <!-- Sidebar toggle button--><a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
      <!-- Navbar Right Menu-->
      <ul class="app-nav">
          <li class=""><a href="" style="color: white" class="app-nav__item nav-link">Commission: {{ request.user|commission_count|floatformat:2 }}</a></li>

        <li class="dropdown"><a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
          <ul class="dropdown-menu settings-menu dropdown-menu-right">
            <li><a class="dropdown-item" href="{% url 'School:home'%}"><i class="fa fa-cog fa-lg"></i> Home</a></li>
{#            <li><a class="dropdown-item" href="{% url 'sms:profile'%}"><i class="fa fa-user fa-lg"></i> Profile</a></li>#}
            <li><a class="dropdown-item" href="{% url 'salesperson:sales_logout'%}"><i class="fa fa-sign-out fa-lg"></i> Logout</a></li>
          </ul>
        </li>
      </ul>
    </header>

salesperson/templates/sales_layouts/roberms_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Roberms: all in one business solution</title>
    <link rel="shortcut icon" href="{% static 'images/robermss.ico' type='image/x-icon' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <script>
    addEventListener("load", function () {
      setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
      window.scrollTo(0, 1);
    }
  </script>

      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="all">
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all">
  <link href="//fonts.googleapis.com/css?family=Fira+Sans:400,500,600,700" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,600" rel="stylesheet">
      {% block additional_styles %}
      {% endblock %}
  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
  {% include 'layouts/top_nav.html' %}

  <br>
  <br>
  <br>
  {% block content %}

  {% endblock %}

  <script rel="script" src="{% static 'js/jquery-3.4.1.js' %}"> </script>
  {% block additional_scripts %}

  {% endblock %}
</body>
</html>

salesperson/templates/sales_layouts/side_nav.html
{% load static %}

<div hidden>
    {% url 'salesperson:dashboard' as dashboard %}
    {% url 'salesperson:clients' as clients %}
    {% url 'salesperson:all_top_ups' as all_top_ups %}
    {% url 'salesperson:account_usage' as account_usage %}
    {% url 'salesperson:my_companies' as my_companies %}
</div>
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
      <ul class="app-menu">
        <li>
            <a {% if request.path == dashboard %} class="app-menu__item active"
               {% else %}
                      class="app-menu__item"
               {% endif %} href="{{ dashboard }}">
                <i class="app-menu__icon fa fa-dashboard"></i>
                <span class="app-menu__label">Dashboard</span></a>
        </li>

      <li>
            <a {% if request.path == clients %} class="app-menu__item active"
               {% else %}
                      class="app-menu__item"
               {% endif %} href="{{ clients }}">
                <i class="app-menu__icon fa fa-dashboard"></i>
                <span class="app-menu__label">Clients</span></a>
        </li>


      <li>
            <a {% if request.path == all_top_ups %} class="app-menu__item active"
               {% else %}
                                                    class="app-menu__item"
          {% endif %}
                     href="{{ all_top_ups }}">
                <i class="app-menu__icon fa fa-dashboard"></i>
                <span class="app-menu__label">Top Ups</span></a>
        </li>

          <li>
              <a {% if request.path == my_companies %} class="app-menu__item active"
              {% else %} class="app-menu__item" {% endif %}
                      href="{{ my_companies }}">
                <i class="app-menu__icon fa fa-building-o"></i>
                <span class="app-menu__label">My Companies</span></a>
          </li>
      </ul>
    </aside>

salesperson/templates/sales_layouts/top_nav.html
{% load static %}
<header>
      <div class="container-fluid">
        <div class="header d-md-flex justify-content-between py-3 pl-2">
          <!-- logo -->
          <div id="logo">
            <h1>
              <a href="{% url 'sms:sms-home' %}">ROBERM'S</a>
            </h1>
          </div>
          <!-- //logo -->
          <!-- nav -->
          <div class="nav_main">
            <nav>
              <label for="drop" class="toggle">Menu</label>
              <input type="checkbox" id="drop" />
              <ul class="menu">
                <li>
                  <a href="{% url 'sms:sms-home' %}" class="active nav-style">Home</a>
                </li>
                <li>
                  <a href="about.html" class="nav-style">About</a>
                </li>
                <li>
                  <a href="{% url 'sms:services' %}" class="nav-style">Services</a>
                </li>
                <li>
                  <!-- First Tier Drop Down -->
                  <label for="drop-2" class="toggle toogle-2 nav-style">Dropdown
                    <span class="fa fa-angle-down" aria-hidden="true"></span>
                  </label>
                  <a href="#" class="nav-style">Dropdown
                    <span class="fa fa-angle-down" aria-hidden="true"></span>
                  </a>
                  <input type="checkbox" id="drop-2" />
                  <ul>
                    <li>
                      <a href="gallery.html" class="drop-text">Gallery</a>
                    </li>
                    <li>
                      <a href="blog.html" class="drop-text">Blog</a>
                    </li>
                    <li>
                      <a href="{% url 'sms:services' %}" class="drop-text">Service</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="{% url 'sms:contact' %}" class="nav-style">Contact</a>
                </li>
              </ul>
            </nav>
          </div>
          <!-- //nav -->
        </div>
      </div>
    </header>

{#<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" style="background: #e8e8e8 !important;" id="ftco-navbar">#}
{#	    <div class="container">#}
{#	      <a class="navbar-brand" href="{%url 'sms:apps'%}">Roberms<span></span></a>#}
{#	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">#}
{#	        <span class="oi oi-menu"></span> Menu#}
{#	      </button>#}
{##}
{#	      <div class="collapse navbar-collapse" id="ftco-nav">#}
{#	        <ul class="navbar-nav nav ml-auto">#}
{#	          <li class="nav-item"><a href="{%url 'sms:sms-home'%}" class="nav-link"><span>Home</span></a></li>#}
{#            <!-- <li class="nav-item"><a href="#about-section" class="nav-link"><span>About</span></a></li>#}
{##}
{#	          <li class="nav-item"><a href="#services-section" class="nav-link"><span>Services</span></a></li> -->#}
{#	          <!-- <li class="nav-item"><a href="#projects-section" class="nav-link"><span>Projects</span></a></li> -->#}
{#	          <!-- <li class="nav-item"><a href="#testimony-section" class="nav-link"><span>Testimony</span></a></li> -->#}
{#	          <!-- <li class="nav-item"><a href="#blog-section" class="nav-link"><span>Blog</span></a></li> -->#}
{#	          <!-- <li class="nav-item"><a href="#contact-section" class="nav-link"><span>Contact</span></a></li>#}
{#            <li class="nav-item"><a href="{%url 'sms:register'%}" class="nav-link"><span>Sign up</span></a></li> -->#}
{#            <li class="nav-item login"><a href="{%url 'sms:logout'%}" class="nav-link"><span>Sign out</span></a></li>#}
{#	        </ul>#}
{#	      </div>#}
{#	    </div>#}
{#	  </nav>#}